### PR TITLE
Updated to reflect the latest location and sponsor (IRESS)

### PR DESCRIPTION
**Pull request by anevis**
Updated to reflect the latest location and sponsor (IRESS)

### CODE REVIEW

**Comment by anevis** [comment]
Preview URL: https://anevis.github.io/sypy.github.com/

**Comment by ivanteoh** [comment]
@anevis Could you have a space between IRESS and |? Thanks.
screen shot 2018-11-20 at 10 31 42 am

**Comment by ivanteoh** [comment]
@anevis I don't have permission to add you as member of the sypy repo. @djay could you add @anevis as a member for updating the site? By the way, who is managing the 'http://sypy.org/' it seem down.

**Comment by djay** [comment]
@ivanteoh I made you an admin which seemed to make more sense. You might want to ask the other organisers to join

**Comment by djay** [comment]
@ivanteoh I don't run the meetup anymore. I'm not sure who owned the domain. @Julian-O maybe?

**Comment by djay** [comment]
@arterrey or was it you who owned the domain? I looked in my godaddy and can't find it

**Comment by ivanteoh** [comment]
@anevis we assign you as admin for this repo.

**Comment by Julian-O** [comment]
> @ivanteoh I don't run the meetup anymore. I'm not sure who owned the domain. @Julian-O maybe?

Not me.

**Comment by arterrey** [comment]
not me either

**Comment by Julian-O** [comment]
I believe sypy.org is just pointing to github.io. We aren't hosting a server, just a domain name.

Doesn't explain why it is down, even though https://status.github.com/messages is all okay.

Did someone play with the Github settings? Want to rollback the (innocent looking) last couple of merges to see if they are breaking it?

**Comment by ivanteoh** [comment]
I didn't touch the settings and I saw the warning as below in the settings.

screen_shot_2018-11-20_at_3_21_50_pm

**Comment by Julian-O** [comment]
Okay, so I think it is clear that this is the situation:

sypy.org should have a DNS record that conforms to GitHub.io custom domain configuration rules [here](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).

However, when using their [trouble-shooting guide](https://help.github.com/articles/troubleshooting-custom-domains/) it is clearly misconfigured.

I don't know whether it is misconfigured because GitHub changed the IP address (and so it is just out of date, which can be prevented by using a ALIASor ANAME record instead of an A record.) or because something else affected the set-up.

The solution seems to be someone (@ivanteoh?) should email the technical contact from the [DNS record](https://centralops.net/co/nslookup.aspx?domain=sypy.org&type=255&server=default-resolver&class=1&port=53&timeout=5000), and ask them to get the owner to contact you.

Then ask the owner (presumably one of us who has forgotten - or @chewxy?) to update the DNS records according to the GitHub guidelines.

**Comment by anevis** [comment]
Hi all,
Thanks for jumping on this, the domain is owned by Mark Rees (I looked up GoDaddy's whois).
The site has been not been stable for a few weeks now.

**Comment by anevis** [comment]
I'll contact Mark Rees to sort out this

**Pull request merged**
